/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import * as THREE from "three";
import React, { useEffect, useMemo, useRef } from "react";
import { useGLTF, useTexture } from "@react-three/drei";
import { GLTF } from "three-stdlib";
import { useFrame } from "@react-three/fiber";
import gsap from "gsap";


type SkateboardProps = {
  deckTextureURL: string;
  deckTextureURLs: string[];
  wheelTextureURL: string;
  wheelTextureURLs: string[];
  truckColor: string;
  boltColor: string;
  constantWheelSpin?: boolean;
};
type GLTFResult = GLTF & {
  nodes: {
    GripTape: THREE.Mesh;
    Wheel1: THREE.Mesh;
    Wheel2: THREE.Mesh;
    Deck: THREE.Mesh;
    Wheel4: THREE.Mesh;
    Bolts: THREE.Mesh;
    Wheel3: THREE.Mesh;
    Baseplates: THREE.Mesh;
    Truck1: THREE.Mesh;
    Truck2: THREE.Mesh;
  };
  materials: Record<string, THREE.Material>;
};

export function Skateboard({
  deckTextureURL,
  deckTextureURLs,
  wheelTextureURL,
  wheelTextureURLs,
  truckColor,
  boltColor,
  constantWheelSpin = false,
}: SkateboardProps) {
  const wheelsRef = useRef<THREE.Object3D[]>([]);


  const { nodes} = useGLTF("/skateboard.gltf") as GLTFResult;

  const wheeltextures = useTexture(wheelTextureURLs);
  wheeltextures.forEach((texture)=>{
    texture.flipY=false;
    texture.colorSpace=THREE.SRGBColorSpace
  })

  const wheelTextureIndex = wheelTextureURLs.findIndex((url)=>url===wheelTextureURL);
  const wheeltexture = wheeltextures[wheelTextureIndex];

  const decktextures = useTexture(deckTextureURLs);
  decktextures.forEach((texture)=>{
    texture.flipY=false;
    texture.colorSpace=THREE.SRGBColorSpace
  })

  const deckTextureIndex = deckTextureURLs.findIndex((url)=>url===deckTextureURL);
  const decktexture = decktextures[deckTextureIndex];

  const gripTapeDiffuse = useTexture("/skateboard/griptape-diffuse.webp");
  const gripTapeRoughness = useTexture("/skateboard/griptape-roughness.webp");


  const gripTapeMaterial = useMemo(() => {
    const material = new THREE.MeshStandardMaterial({
      map: gripTapeDiffuse,
      bumpMap: gripTapeRoughness,
      roughnessMap: gripTapeRoughness,
      bumpScale: 3.5,
      roughness: 0.8,
      color: "#555555",
    });

    if (gripTapeDiffuse) {
      gripTapeDiffuse.wrapS = THREE.RepeatWrapping;
      gripTapeDiffuse.wrapT = THREE.RepeatWrapping;
      gripTapeDiffuse.repeat.set(9, 9);
      gripTapeDiffuse.needsUpdate = true;

      gripTapeRoughness.wrapS = THREE.RepeatWrapping;
      gripTapeRoughness.wrapT = THREE.RepeatWrapping;
      gripTapeRoughness.repeat.set(9, 9);
      gripTapeRoughness.needsUpdate = true;

      gripTapeRoughness.anisotropy = 8;
    }

    return material;
  }, [gripTapeDiffuse, gripTapeRoughness]);

  const boltMaterial = useMemo(
    () =>
      new THREE.MeshStandardMaterial({
        color: boltColor,
        metalness: 0.5,
        roughness: 0.3,
      }),
    [boltColor]
  );

  const metalNormal = useTexture("/skateboard/metal-normal.avif");
  metalNormal.wrapS = 1000;
  metalNormal.wrapT = 1000;
  metalNormal.anisotropy = 8;
  metalNormal.repeat.set(8, 8);

  const truckMaterial = useMemo(
    () =>
      new THREE.MeshStandardMaterial({
        color: truckColor,
        normalMap: metalNormal,
        normalScale: new THREE.Vector2(0.3, 0.3),
        metalness: 0.8,
        roughness: 0.25,
      }),
    [truckColor, metalNormal]
  );


  const deckMaterial = useMemo(
    () =>
      new THREE.MeshStandardMaterial({
        map: decktexture,
        roughness: 0.1,
      }),
    [decktexture]
  );


  const wheelMaterial = useMemo(
    () =>
      new THREE.MeshStandardMaterial({
        map: wheeltexture,
        roughness: 0.35,
      }),
    [wheeltexture]
  );

  const addtoWheel = (ref:THREE.Object3D| null) =>{
    if(ref && !wheelsRef.current.includes(ref)){
      wheelsRef.current.push(ref);
    }
  }
  useFrame(()=>{
    if(!wheelsRef.current|| !constantWheelSpin) return;
    for(const wheel of wheelsRef.current){
      wheel.rotation.x+=0.5;
    }
  })
  useEffect(()=>{
    if(!wheelsRef.current|| constantWheelSpin) return;
    for(const wheel of wheelsRef.current){
      gsap.to(wheel.rotation,{
        x:"-=30",
        duration:2.5,
        ease: "circ.out"
      })
    }
  },[constantWheelSpin])

  return (
    <group dispose={null}>
      <group name="Scene">
        <mesh
          name="GripTape"
          castShadow
          receiveShadow
          geometry={nodes.GripTape.geometry}
          material={gripTapeMaterial}
          position={[0, 0.286, -0.002]}
        />
        <mesh
          name="Wheel1"
          castShadow
          receiveShadow
          geometry={nodes.Wheel1.geometry}
          material={wheelMaterial}
          position={[0.238, 0.086, 0.635]}
          ref={addtoWheel}
        />
        <mesh
          name="Wheel2"
          castShadow
          receiveShadow
          geometry={nodes.Wheel2.geometry}
          material={wheelMaterial}
          position={[-0.237, 0.086, 0.635]}
          ref={addtoWheel}
        />
        <mesh
          name="Deck"
          castShadow
          receiveShadow
          geometry={nodes.Deck.geometry}
          material={deckMaterial}
          position={[0, 0.271, -0.002]}
        />
        <mesh
          name="Wheel4"
          castShadow
          receiveShadow
          geometry={nodes.Wheel4.geometry}
          material={wheelMaterial}
          position={[-0.238, 0.086, -0.635]}
          rotation={[Math.PI, 0, Math.PI]}
          ref={addtoWheel}
        />
        <mesh
          name="Bolts"
          castShadow
          receiveShadow
          geometry={nodes.Bolts.geometry}
          material={boltMaterial}
          position={[0, 0.198, 0]}
          rotation={[Math.PI, 0, Math.PI]}
        />
        <mesh
          name="Wheel3"
          castShadow
          receiveShadow
          geometry={nodes.Wheel3.geometry}
          material={wheelMaterial}
          position={[0.237, 0.086, -0.635]}
          rotation={[Math.PI, 0, Math.PI]}
          ref={addtoWheel}
        />
        <mesh
          name="Baseplates"
          castShadow
          receiveShadow
          geometry={nodes.Baseplates.geometry}
          material={truckMaterial}
          position={[0, 0.211, 0]}
        />
        <mesh
          name="Truck1"
          castShadow
          receiveShadow
          geometry={nodes.Truck1.geometry}
          material={truckMaterial}
          position={[0, 0.101, -0.617]}
        />
        <mesh
          name="Truck2"
          castShadow
          receiveShadow
          geometry={nodes.Truck2.geometry}
          material={truckMaterial}
          position={[0, 0.101, 0.617]}
          rotation={[Math.PI, 0, Math.PI]}
        />
      </group>
    </group>
  );
}

useGLTF.preload("/skateboard.gltf");
