// Code generated by Slice Machine. DO NOT EDIT.

import dynamic from "next/dynamic";

export const components = {
  hero: dynamic(() => import("./Hero")),
  product_grid: dynamic(() => import("./ProductGrid")),
  team_gr: dynamic(() => import("./TeamGr")),
  text_image: dynamic(() => import("./TextImage")),
  video: dynamic(() => import("./Video")),
};
